# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_cabeceras'),
    ]

    operations = [
        migrations.CreateModel(
            name='mprincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
